### ISSUE TITLE
migrating the app from create react app to vite

### ISSUE THREAD

**Issue by Gourav-21** [ishitaraina1807/Reading-Matters#20]
## Problem
The frontend has been created with create react app which is not maintained by the react team anymore
so, It is thus unlikely that these errors will ever be fixed.

![image](https://github.com/ishitaraina1807/Reading-Matters/assets/107918791/558d8640-1b90-483e-97c1-63a3a5942547)
![image](https://github.com/ishitaraina1807/Reading-Matters/assets/107918791/53e0b93b-65dd-4aa3-b94e-5f152937c7f3)

## Suggestion
I suggest we should migrate/switch the frontend code from create react app to vite that would not only make the code futureproof but will also help speed up the development process

**Comment by ishitaraina1807** [comment]
You can go ahead with the same. @Gourav-21
